//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriconneReALLTLInstaller.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>BepInEx/Translation/en/Text/_Postprocessors.txt</string>
  <string>BepInEx/Translation/en/Text/_Preprocessors.txt</string>
  <string>BepInEx/Translation/en/Text/_Substitutions.txt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ignoreFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ignoreFiles"]));
            }
            set {
                this["ignoreFiles"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>BepInEx/config/AutoTranslatorConfig.ini</string>
  <string>BepInEx/config/PriconneTLFixup.cfg</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection configFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["configFiles"]));
            }
        }
        
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nMulti-Account · ALL-TL (EN/TH) edition — fork by HetCreep\r\nBased on tynave/Pricon" +
            "neReTL-Installer\r\nInspired by touanu/PriconeTL_Updater\r\n\r\nAll assets used in thi" +
            "s application are properties of CyberAgent, Inc., Cygames, Inc. / their respectiv" +
            "e creators.")]
        public string aboutText {
            get {
                return ((string)(this["aboutText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Install")]
        public string installMode {
            get {
                return ((string)(this["installMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Installs the translation patch.\r\nKeeps config files, ignored files and \r\nany user" +
            " created files already present.")]
        public string installModeDescription {
            get {
                return ((string)(this["installModeDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Uninstall")]
        public string uninstallMode {
            get {
                return ((string)(this["uninstallMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Removes the translation patch.\r\nKeeps any user created files.\r\nDepending on the o" +
            "ptions selected, keeps or removes config/ignored/interop files.")]
        public string uninstallModeDescription {
            get {
                return ((string)(this["uninstallModeDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reinstall")]
        public string reinstallMode {
            get {
                return ((string)(this["reinstallMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Removes the translation patch, and then installs the latest version.\r\nKeeps any u" +
            "ser created files.\r\nDepending on the options selected, keeps or removes config/i" +
            "gnored/interop files.")]
        public string reinstallModeDescription {
            get {
                return ((string)(this["reinstallModeDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Update")]
        public string updateMode {
            get {
                return ((string)(this["updateMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Updates the current translation patch installation by removing the the current ve" +
            "rsion and installing the latest.\r\nKeeps user files, as well as config/ignored fi" +
            "les.")]
        public string updateModeDescription {
            get {
                return ((string)(this["updateModeDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public string disabledMode {
            get {
                return ((string)(this["disabledMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operation disabled due to an error.\r\nSee log for details.")]
        public string disabledModeDescription {
            get {
                return ((string)(this["disabledModeDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Launch Game")]
        public string launchMode {
            get {
                return ((string)(this["launchMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Launches the game using the selected launcher.")]
        public string launchModeDescrption {
            get {
                return ((string)(this["launchModeDescrption"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No Operation")]
        public string noOperationMode {
            get {
                return ((string)(this["noOperationMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No operation selected.")]
        public string noOperationModeDescription {
            get {
                return ((string)(this["noOperationModeDescription"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool launchState {
            get {
                return ((bool)(this["launchState"]));
            }
            set {
                this["launchState"] = value;
            }
        }
        
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fastLauncherLink {
            get {
                return ((string)(this["fastLauncherLink"]));
            }
            set {
                this["fastLauncherLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" />")]
        public global::System.Collections.Specialized.StringCollection fastLauncherLinks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["fastLauncherLinks"]));
            }
            set {
                this["fastLauncherLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5.0.0")]
        public string LastKnownVersion {
            get {
                return ((string)(this["LastKnownVersion"]));
            }
            set {
                this["LastKnownVersion"] = value;
            }
        }
        
        

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedPatchSource {
            get {
                return ((int)(this["selectedPatchSource"]));
            }
            set {
                this["selectedPatchSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkForInstallerUpdates {
            get {
                return ((bool)(this["checkForInstallerUpdates"]));
            }
            set {
                this["checkForInstallerUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showLogChecked {
            get {
                return ((bool)(this["showLogChecked"]));
            }
            set {
                this["showLogChecked"] = value;
            }
        }
        
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DMMConfigPath {
            get {
                return ((string)(this["DMMConfigPath"]));
            }
            set {
                this["DMMConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GithubAPIKey {
            get {
                return ((string)(this["GithubAPIKey"]));
            }
            set {
                this["GithubAPIKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string versionCacheJson {
            get {
                return ((string)(this["versionCacheJson"]));
            }
            set {
                this["versionCacheJson"] = value;
            }
        }
    }
}
